use std::{collections::BTreeMap, pin::Pin};

use anyhow::{Context, Result};
use clawcr_protocol::{
    ModelRequest, ModelResponse, ResponseContent, ResponseExtra, ResponseMetadata, StopReason,
    StreamEvent, Usage,
};
use futures::{Stream, StreamExt};
use reqwest_eventsource::{Event, EventSource};
use serde::Deserialize;
use serde_json::Value;

use super::{
    OpenAIChatCompletionChoice, OpenAIChatCompletionCustomToolCall,
    OpenAIChatCompletionFunctionCall, OpenAIChatCompletionMessage,
    OpenAIChatCompletionMessageToolCall, OpenAIChoiceLogprobs, OpenAICompletionUsage,
    OpenAIProvider, build_provider_specific_response_payload, build_request, parse_finish_reason,
    parse_tool_use,
};
use crate::text_normalization::{TaggedTextFragment, TaggedTextParser};

/// <https://developers.openai.com/api/reference/resources/chat/subresources/completions/streaming-events>
/// Represents a streamed chunk of a chat completion response returned by the model, based on the provided input.
/// - id: string
///   A unique identifier for the chat completion. Each chunk has the same ID.
/// - choices: array of object
///   A list of chat completion choices. Can contain more than one elements if n is greater than 1. Can also be empty for the last chunk if you set stream_options: {"include_usage": true}.
///   - delta: object
///     A chat completion delta generated by streamed model responses.
///     - content: optional string
///       The contents of the chunk message.
///     - refusal: optional string
///       The refusal message generated by the model.
///     - role: optional "developer" or "system" or "user" or "assistant" or "tool"
///       The role of the author of this message.
///     - tool_calls: optional array of
///       - index: number
///       - id: optional string
///         The ID of the tool call.
///       - function: optional object
///         - arguments: optional string
///           The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
///         - name: optional string
///           The name of the function to call.
///       - type: optional "function"
///         The type of the tool. Currently, only function is supported.
///    - finish_reason: "stop" or "length" or "tool_calls" or "content_filter" or "function_call"
///       The reason the model stopped generating tokens. This will be stop if the model hit a natural stop point or a provided stop sequence, length if the maximum number of tokens specified in the request was reached, content_filter if content was omitted due to a flag from our content filters, tool_calls if the model called a tool, or function_call (deprecated) if the model called a function.
///    - index: number
///      The index of the choice in the list of choices.
///    - logprobs: optional object
///      Log probability information for the choice.
/// - created: number
/// The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.
/// - model: string
/// The model to generate the completion.
/// - object: "chat.completion.chunk"
/// The object type, which is always chat.completion.chunk
/// - service_tier: optional "auto" or "default" or "flex" or "scale" or "priority"
/// - usage: optional CompletionUsage
pub(super) async fn completion_stream(
    provider: &OpenAIProvider,
    request: ModelRequest,
) -> Result<Pin<Box<dyn Stream<Item = Result<StreamEvent>> + Send>>> {
    let body = build_request(&request, true);
    tracing::info!(
        provider = "openai",
        api_base = %provider.base_url,
        model = %request.model,
        messages = request.messages.len(),
        tools = request.tools.as_ref().map_or(0, Vec::len),
        max_tokens = request.max_tokens,
        http_body = %body,
        "sending openai streaming request"
    );

    let event_source = EventSource::new(provider.request_builder(&body))
        .context("failed to create openai event source")?;
    let stream = async_stream::try_stream! {
        let mut state = ChatCompletionStreamState::default();

        futures::pin_mut!(event_source);
        while let Some(event) = event_source.next().await {
            let event = event.map_err(|error| {
                anyhow::anyhow!("openai stream error for model {}: {error}", request.model)
            })?;

            match event {
                Event::Open => {}
                Event::Message(message) => {
                    if message.data == "[DONE]" {
                        break;
                    }

                    let chunk: ChatCompletionStreamChunk = serde_json::from_str(&message.data)
                        .map_err(|error| {
                            anyhow::anyhow!("failed to parse openai stream chunk: {error}")
                        })?;

                    for stream_event in state.apply_chunk(chunk) {
                        yield stream_event;
                    }
                }
            }
        }

        yield StreamEvent::MessageDone {
            response: state.into_response(),
        };
    };

    Ok(Box::pin(stream))
}

#[derive(Debug, Default)]
struct ChatCompletionStreamState {
    response_id: String,
    created: Option<u64>,
    model: Option<String>,
    object: Option<String>,
    service_tier: Option<String>,
    system_fingerprint: Option<String>,
    text: StreamTextBlock,
    text_parser: TaggedTextParser,
    reasoning: StreamTextBlock,
    refusal: String,
    role: Option<String>,
    tool_calls: BTreeMap<u32, PartialToolCall>,
    choice_metadata: BTreeMap<u32, StreamChoiceMetadata>,
    finish_reason: Option<StopReason>,
    usage: Option<Usage>,
}

impl ChatCompletionStreamState {
    fn apply_chunk(&mut self, chunk: ChatCompletionStreamChunk) -> Vec<StreamEvent> {
        let mut events = Vec::new();

        if self.response_id.is_empty() {
            if let Some(id) = chunk.id {
                self.response_id = id;
            }
        }
        if self.created.is_none() {
            self.created = chunk.created;
        }
        if self.model.is_none() {
            self.model = chunk.model;
        }
        if self.object.is_none() {
            self.object = chunk.object;
        }
        if self.service_tier.is_none() {
            self.service_tier = chunk.service_tier;
        }
        if self.system_fingerprint.is_none() {
            self.system_fingerprint = chunk.system_fingerprint;
        }

        if let Some(usage) = chunk.usage.map(usage_from_completion_usage) {
            self.usage = Some(usage.clone());
            events.push(StreamEvent::UsageDelta(usage));
        }

        for choice in chunk.choices {
            self.apply_choice(choice, &mut events);
        }

        events
    }

    fn apply_choice(&mut self, choice: ChatCompletionStreamChoice, events: &mut Vec<StreamEvent>) {
        let choice_index = choice.index.unwrap_or(0);
        self.choice_metadata.entry(choice_index).or_default().index = Some(choice_index);
        self.choice_metadata
            .entry(choice_index)
            .or_default()
            .logprobs = choice.logprobs.clone();

        if let Some(role) = choice.delta.role.as_deref() {
            self.role = Some(role.to_string());
        }
        if let Some(refusal) = choice.delta.refusal.filter(|refusal| !refusal.is_empty()) {
            self.refusal.push_str(&refusal);
        }

        if let Some(reasoning_content) = choice
            .delta
            .reasoning_content
            .filter(|reasoning_content| !reasoning_content.is_empty())
        {
            self.push_reasoning_delta(reasoning_content, events);
        }

        if let Some(content) = choice.delta.content.filter(|content| !content.is_empty()) {
            for fragment in self.text_parser.consume(&content) {
                match fragment {
                    TaggedTextFragment::Text(text) => self.push_text_delta(text, events),
                    TaggedTextFragment::Reasoning(text) => self.push_reasoning_delta(text, events),
                }
            }
        }

        for tool_call_delta in choice.delta.tool_calls {
            self.apply_tool_call_delta(tool_call_delta, events);
        }

        if let Some(reason) = choice.finish_reason {
            for fragment in self.text_parser.finish() {
                match fragment {
                    TaggedTextFragment::Text(text) => self.push_text_delta(text, events),
                    TaggedTextFragment::Reasoning(text) => self.push_reasoning_delta(text, events),
                }
            }
            self.finish_reason = Some(parse_finish_reason(&reason));
            self.choice_metadata
                .entry(choice_index)
                .or_default()
                .finish_reason = Some(reason);
        }
    }

    fn push_text_delta(&mut self, text: String, events: &mut Vec<StreamEvent>) {
        if text.is_empty() {
            return;
        }
        if !self.text.started {
            self.text.started = true;
            events.push(StreamEvent::TextStart { index: 0 });
        }
        self.text.value.push_str(&text);
        events.push(StreamEvent::TextDelta { index: 0, text });
    }

    fn push_reasoning_delta(&mut self, text: String, events: &mut Vec<StreamEvent>) {
        if text.is_empty() {
            return;
        }
        if !self.reasoning.started {
            self.reasoning.started = true;
            events.push(StreamEvent::ReasoningStart { index: 1 });
        }
        self.reasoning.value.push_str(&text);
        events.push(StreamEvent::ReasoningDelta { index: 1, text });
    }

    fn apply_tool_call_delta(
        &mut self,
        tool_call_delta: ChatCompletionStreamToolCallDelta,
        events: &mut Vec<StreamEvent>,
    ) {
        let ChatCompletionStreamToolCallDelta {
            index,
            id,
            kind,
            function,
            custom,
        } = tool_call_delta;
        let index = index.unwrap_or(0);
        let content_index = (index + 1) as usize;
        let entry = self.tool_calls.entry(index).or_default();

        if let Some(id) = id {
            entry.id = id;
        }
        if let Some(kind) = kind.as_deref().and_then(ToolCallKind::from_wire) {
            entry.kind = kind;
        }

        let mut function_arguments_delta = None;
        if let Some(function) = function {
            if let Some(name) = function.name {
                entry.name = name;
            }

            if let Some(arguments) = function.arguments.filter(|arguments| !arguments.is_empty()) {
                function_arguments_delta = Some(arguments.clone());
                entry.arguments_json.push_str(&arguments);
            }
        }

        let mut custom_input_delta = None;
        if let Some(custom) = custom {
            if let Some(name) = custom.name {
                entry.name = name;
            }
            if let Some(input) = custom.input.filter(|input| !input.is_empty()) {
                custom_input_delta = Some(input.clone());
                entry.arguments_json.push_str(&input);
            }
        }

        if !entry.started && tool_call_delta_starts_block(entry) {
            entry.started = true;
            events.push(StreamEvent::ToolCallStart {
                index: content_index,
                id: entry.id.clone(),
                name: entry.name.clone(),
                input: entry.kind.empty_input(),
            });
        }

        if let Some(arguments) = function_arguments_delta {
            events.push(StreamEvent::ToolCallInputDelta {
                index: content_index,
                partial_json: arguments,
            });
        }
        if let Some(input) = custom_input_delta {
            events.push(StreamEvent::ToolCallInputDelta {
                index: content_index,
                partial_json: input,
            });
        }
    }

    fn metadata(&self) -> ResponseMetadata {
        let mut metadata = ResponseMetadata::default();

        if !self.reasoning.value.is_empty() {
            metadata.extras.push(ResponseExtra::ReasoningText {
                text: self.reasoning.value.clone(),
            });
        }

        if let Some(payload) = self.provider_specific_payload() {
            metadata.extras.push(ResponseExtra::ProviderSpecific {
                provider: "openai".to_string(),
                payload,
            });
        }

        metadata
    }

    fn provider_specific_payload(&self) -> Option<Value> {
        let response = self.as_provider_response();
        build_provider_specific_response_payload(&response)
    }

    fn as_provider_response(&self) -> super::OpenAIChatCompletionResponse {
        super::OpenAIChatCompletionResponse {
            id: self.response_id.clone(),
            choices: self.provider_choices(),
            created: self.created,
            model: self.model.clone(),
            object: self.object.clone(),
            service_tier: self.service_tier.clone(),
            system_fingerprint: self.system_fingerprint.clone(),
            usage: self.usage.as_ref().map(|usage| OpenAICompletionUsage {
                prompt_tokens: usage.input_tokens,
                completion_tokens: usage.output_tokens,
                total_tokens: Some(usage.input_tokens + usage.output_tokens),
                prompt_tokens_details: Some(super::OpenAIPromptTokenDetails {
                    audio_tokens: None,
                    cached_tokens: usage.cache_read_input_tokens,
                }),
                completion_tokens_details: None,
            }),
        }
    }

    fn provider_choices(&self) -> Vec<OpenAIChatCompletionChoice> {
        let message = OpenAIChatCompletionMessage {
            content: if self.text.value.is_empty() {
                None
            } else {
                Some(self.text.value.clone())
            },
            refusal: if self.refusal.is_empty() {
                None
            } else {
                Some(self.refusal.clone())
            },
            role: self.role.clone(),
            annotations: Vec::new(),
            audio: None,
            function_call: None,
            tool_calls: self.provider_tool_calls(),
            reasoning_content: if self.reasoning.value.is_empty() {
                None
            } else {
                Some(self.reasoning.value.clone())
            },
        };

        if self.choice_metadata.is_empty()
            && message.content.is_none()
            && message.refusal.is_none()
            && message.tool_calls.is_empty()
            && self.finish_reason.is_none()
        {
            return Vec::new();
        }

        if self.choice_metadata.is_empty() {
            return vec![OpenAIChatCompletionChoice {
                finish_reason: self
                    .finish_reason
                    .as_ref()
                    .map(stop_reason_to_finish_reason),
                index: Some(0),
                logprobs: None,
                message: Some(message),
            }];
        }

        self.choice_metadata
            .iter()
            .map(|(index, metadata)| OpenAIChatCompletionChoice {
                finish_reason: metadata.finish_reason.clone().or_else(|| {
                    self.finish_reason
                        .as_ref()
                        .map(stop_reason_to_finish_reason)
                }),
                index: Some(*index),
                logprobs: metadata.logprobs.clone(),
                message: Some(message.clone()),
            })
            .collect()
    }

    fn provider_tool_calls(&self) -> Vec<OpenAIChatCompletionMessageToolCall> {
        self.tool_calls
            .values()
            .cloned()
            .map(PartialToolCall::into_provider_tool_call)
            .collect()
    }

    fn ordered_content(
        text: StreamTextBlock,
        tool_calls: BTreeMap<u32, PartialToolCall>,
    ) -> Vec<ResponseContent> {
        let mut content = Vec::new();

        if !text.value.is_empty() {
            content.push(ResponseContent::Text(text.value));
        }

        for tool_call in tool_calls.into_values() {
            let provider_tool_call = tool_call.into_provider_tool_call();
            if let Some(content_block) = parse_tool_use(&provider_tool_call) {
                content.push(content_block);
            }
        }

        content
    }

    fn into_response(self) -> ModelResponse {
        let usage = self.usage.clone().unwrap_or_default();
        let metadata = self.metadata();
        let ChatCompletionStreamState {
            response_id,
            finish_reason,
            text,
            tool_calls,
            ..
        } = self;
        let content = Self::ordered_content(text, tool_calls);

        ModelResponse {
            id: response_id,
            content,
            stop_reason: finish_reason,
            usage,
            metadata,
        }
    }
}

fn tool_call_delta_starts_block(entry: &PartialToolCall) -> bool {
    !entry.id.is_empty() || !entry.name.is_empty() || !entry.arguments_json.is_empty()
}

fn usage_from_completion_usage(usage: OpenAICompletionUsage) -> Usage {
    Usage {
        input_tokens: usage.prompt_tokens,
        output_tokens: usage.completion_tokens,
        cache_creation_input_tokens: None,
        cache_read_input_tokens: usage
            .prompt_tokens_details
            .as_ref()
            .and_then(|details| details.cached_tokens),
    }
}

#[derive(Debug, Default)]
struct StreamTextBlock {
    value: String,
    started: bool,
}

#[derive(Debug, Clone, Default)]
struct PartialToolCall {
    id: String,
    name: String,
    arguments_json: String,
    started: bool,
    kind: ToolCallKind,
}

impl PartialToolCall {
    fn into_provider_tool_call(self) -> OpenAIChatCompletionMessageToolCall {
        match self.kind {
            ToolCallKind::Function => OpenAIChatCompletionMessageToolCall {
                id: self.id,
                kind: "function".to_string(),
                function: Some(OpenAIChatCompletionFunctionCall {
                    arguments: self.arguments_json,
                    name: self.name,
                }),
                custom: None,
            },
            ToolCallKind::Custom => OpenAIChatCompletionMessageToolCall {
                id: self.id,
                kind: "custom".to_string(),
                function: None,
                custom: Some(OpenAIChatCompletionCustomToolCall {
                    input: self.arguments_json,
                    name: self.name,
                }),
            },
        }
    }
}

#[derive(Debug, Default)]
struct StreamChoiceMetadata {
    index: Option<u32>,
    finish_reason: Option<String>,
    logprobs: Option<OpenAIChoiceLogprobs>,
}

#[derive(Debug, Clone, Copy, Default)]
enum ToolCallKind {
    #[default]
    Function,
    Custom,
}

impl ToolCallKind {
    fn from_wire(value: &str) -> Option<Self> {
        match value {
            "function" => Some(Self::Function),
            "custom" => Some(Self::Custom),
            _ => None,
        }
    }

    fn empty_input(self) -> Value {
        match self {
            Self::Function => Value::Object(serde_json::Map::new()),
            Self::Custom => Value::String(String::new()),
        }
    }
}

#[derive(Debug, Deserialize)]
struct ChatCompletionStreamChunk {
    #[serde(default)]
    id: Option<String>,
    #[serde(default)]
    created: Option<u64>,
    #[serde(default)]
    model: Option<String>,
    #[serde(default)]
    object: Option<String>,
    #[serde(default)]
    service_tier: Option<String>,
    #[serde(default)]
    system_fingerprint: Option<String>,
    #[serde(default)]
    choices: Vec<ChatCompletionStreamChoice>,
    #[serde(default)]
    usage: Option<OpenAICompletionUsage>,
}

#[derive(Debug, Default, Deserialize)]
struct ChatCompletionStreamChoice {
    #[serde(default)]
    delta: ChatCompletionStreamDelta,
    #[serde(default)]
    index: Option<u32>,
    #[serde(default)]
    finish_reason: Option<String>,
    #[serde(default)]
    logprobs: Option<OpenAIChoiceLogprobs>,
}

#[derive(Debug, Default, Deserialize)]
struct ChatCompletionStreamDelta {
    #[serde(default)]
    role: Option<String>,
    #[serde(default)]
    content: Option<String>,
    #[serde(default)]
    reasoning_content: Option<String>,
    #[serde(default)]
    refusal: Option<String>,
    #[serde(default)]
    tool_calls: Vec<ChatCompletionStreamToolCallDelta>,
}

#[derive(Debug, Default, Deserialize)]
struct ChatCompletionStreamToolCallDelta {
    #[serde(default)]
    index: Option<u32>,
    #[serde(default)]
    id: Option<String>,
    #[serde(rename = "type", default)]
    kind: Option<String>,
    #[serde(default)]
    function: Option<ChatCompletionStreamFunctionDelta>,
    #[serde(default)]
    custom: Option<ChatCompletionStreamCustomDelta>,
}

#[derive(Debug, Default, Deserialize)]
struct ChatCompletionStreamFunctionDelta {
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    arguments: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
struct ChatCompletionStreamCustomDelta {
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    input: Option<String>,
}

fn stop_reason_to_finish_reason(reason: &StopReason) -> String {
    match reason {
        StopReason::ToolUse => "tool_calls".to_string(),
        StopReason::MaxTokens => "length".to_string(),
        StopReason::EndTurn => "stop".to_string(),
        StopReason::StopSequence => "content_filter".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use pretty_assertions::assert_eq;
    use serde_json::json;

    use super::*;

    #[test]
    fn text_chunks_accumulate_into_response() {
        let mut state = ChatCompletionStreamState::default();

        let events = state.apply_chunk(parse_chunk(json!({
            "id": "chatcmpl-123",
            "choices": [
                {
                    "delta": {
                        "role": "assistant",
                        "content": ""
                    }
                }
            ]
        })));
        assert!(events.is_empty());

        let events = state.apply_chunk(parse_chunk(json!({
            "choices": [
                {
                    "delta": {
                        "content": "Hello"
                    }
                }
            ]
        })));
        assert_eq!(events.len(), 2);
        assert!(matches!(&events[0], StreamEvent::TextStart { index: 0 }));
        assert!(matches!(
            &events[1],
            StreamEvent::TextDelta { index: 0, text } if text == "Hello"
        ));

        state.apply_chunk(parse_chunk(json!({
            "choices": [
                {
                    "delta": {
                        "content": " world"
                    },
                    "finish_reason": "stop"
                }
            ]
        })));

        let response = state.into_response();
        assert_eq!(response.id, "chatcmpl-123");
        assert_eq!(response.stop_reason, Some(StopReason::EndTurn));
        assert_eq!(response.usage.input_tokens, 0);
        assert_eq!(response.usage.output_tokens, 0);
        assert_eq!(response.content.len(), 1);
        match &response.content[0] {
            ResponseContent::Text(text) => assert_eq!(text, "Hello world"),
            other => panic!("expected text content, got {other:?}"),
        }
    }

    #[test]
    fn tool_call_block_starts_before_arguments_arrive() {
        let mut state = ChatCompletionStreamState::default();

        let events = state.apply_chunk(parse_chunk(json!({
            "id": "chatcmpl-456",
            "choices": [
                {
                    "delta": {
                        "tool_calls": [
                            {
                                "index": 0,
                                "id": "call_123",
                                "function": {
                                    "name": "get_weather"
                                }
                            }
                        ]
                    }
                }
            ]
        })));

        assert_eq!(events.len(), 1);
        assert!(matches!(
            &events[0],
            StreamEvent::ToolCallStart { index: 1, id, name, input }
            if id == "call_123" && name == "get_weather" && input == &json!({})
        ));

        let events = state.apply_chunk(parse_chunk(json!({
            "choices": [
                {
                    "delta": {
                        "tool_calls": [
                            {
                                "index": 0,
                                "function": {
                                    "arguments": "{\"city\":\"Boston\"}"
                                }
                            }
                        ]
                    },
                    "finish_reason": "tool_calls"
                }
            ]
        })));

        assert_eq!(events.len(), 1);
        assert!(matches!(
            &events[0],
            StreamEvent::ToolCallInputDelta {
                index: 1,
                partial_json,
            } if partial_json == "{\"city\":\"Boston\"}"
        ));

        let response = state.into_response();
        assert_eq!(response.stop_reason, Some(StopReason::ToolUse));
        assert_eq!(response.content.len(), 1);
        match &response.content[0] {
            ResponseContent::ToolUse { id, name, input } => {
                assert_eq!(id, "call_123");
                assert_eq!(name, "get_weather");
                assert_eq!(input, &json!({"city": "Boston"}));
            }
            other => panic!("expected tool content, got {other:?}"),
        }
    }

    #[test]
    fn usage_chunks_and_malformed_tool_json_are_handled() {
        let mut state = ChatCompletionStreamState::default();

        let events = state.apply_chunk(parse_chunk(json!({
            "id": "chatcmpl-789",
            "usage": {
                "prompt_tokens": 11,
                "completion_tokens": 7,
                "total_tokens": 18,
                "prompt_tokens_details": {
                    "cached_tokens": 3
                }
            }
        })));

        assert_eq!(events.len(), 1);
        assert!(matches!(
            &events[0],
            StreamEvent::UsageDelta(Usage {
                input_tokens: 11,
                output_tokens: 7,
                cache_read_input_tokens: Some(3),
                ..
            })
        ));

        let events = state.apply_chunk(parse_chunk(json!({
            "choices": [
                {
                    "delta": {
                        "tool_calls": [
                            {
                                "index": 0,
                                "id": "call_bad",
                                "function": {
                                    "name": "broken_tool",
                                    "arguments": "{"
                                }
                            }
                        ]
                    }
                }
            ]
        })));

        assert_eq!(events.len(), 2);

        let response = state.into_response();
        assert_eq!(response.usage.input_tokens, 11);
        assert_eq!(response.usage.output_tokens, 7);
        assert_eq!(response.usage.cache_read_input_tokens, Some(3));
        assert_eq!(response.content.len(), 1);
        match &response.content[0] {
            ResponseContent::ToolUse { id, name, input } => {
                assert_eq!(id, "call_bad");
                assert_eq!(name, "broken_tool");
                assert_eq!(input, &json!({}));
            }
            other => panic!("expected tool content, got {other:?}"),
        }
        assert!(response.metadata.extras.iter().any(|extra| matches!(
            extra,
            ResponseExtra::ProviderSpecific { provider, payload }
            if provider == "openai" && payload["usage"]["prompt_tokens"] == json!(11)
        )));
    }

    #[test]
    fn chunks_without_choices_are_ignored_safely() {
        let mut state = ChatCompletionStreamState::default();

        let events = state.apply_chunk(parse_chunk(json!({
            "id": "chatcmpl-empty",
            "object": "chat.completion.chunk",
            "created": 1741569952,
            "model": "gpt-5.4"
        })));

        assert!(events.is_empty());

        let response = state.into_response();
        assert_eq!(response.id, "chatcmpl-empty");
        assert!(response.content.is_empty());
        assert!(response.metadata.extras.iter().any(|extra| matches!(
            extra,
            ResponseExtra::ProviderSpecific { provider, payload }
            if provider == "openai"
                && payload["object"] == json!("chat.completion.chunk")
                && payload["model"] == json!("gpt-5.4")
        )));
    }

    #[test]
    fn interleaved_text_and_tool_call_chunks_preserve_event_order() {
        let mut state = ChatCompletionStreamState::default();

        let events = state.apply_chunk(parse_chunk(json!({
            "id": "chatcmpl-mixed",
            "choices": [
                {
                    "delta": {
                        "content": "Let me "
                    }
                }
            ]
        })));
        assert_eq!(events.len(), 2);

        let events = state.apply_chunk(parse_chunk(json!({
            "choices": [
                {
                    "delta": {
                        "tool_calls": [
                            {
                                "index": 0,
                                "id": "call_mix",
                                "type": "function",
                                "function": {
                                    "name": "lookup_weather"
                                }
                            }
                        ]
                    }
                }
            ]
        })));
        assert_eq!(events.len(), 1);
        assert!(matches!(
            &events[0],
            StreamEvent::ToolCallStart { index: 1, id, name, .. }
            if id == "call_mix" && name == "lookup_weather"
        ));

        let events = state.apply_chunk(parse_chunk(json!({
            "choices": [
                {
                    "delta": {
                        "content": "check that",
                        "tool_calls": [
                            {
                                "index": 0,
                                "function": {
                                    "arguments": "{\"city\":\"Boston\"}"
                                }
                            }
                        ]
                    },
                    "finish_reason": "tool_calls"
                }
            ]
        })));
        assert_eq!(events.len(), 2);
        assert!(matches!(
            &events[0],
            StreamEvent::TextDelta { index: 0, text } if text == "check that"
        ));
        assert!(matches!(
            &events[1],
            StreamEvent::ToolCallInputDelta { index: 1, partial_json }
            if partial_json == "{\"city\":\"Boston\"}"
        ));

        let response = state.into_response();
        assert_eq!(response.stop_reason, Some(StopReason::ToolUse));
        assert_eq!(response.content.len(), 2);
    }

    #[test]
    fn custom_tool_call_stream_uses_string_input() {
        let mut state = ChatCompletionStreamState::default();

        let events = state.apply_chunk(parse_chunk(json!({
            "choices": [
                {
                    "delta": {
                        "tool_calls": [
                            {
                                "index": 0,
                                "id": "call_custom",
                                "type": "custom",
                                "custom": {
                                    "name": "draft_sql",
                                    "input": "select *"
                                }
                            }
                        ]
                    },
                    "finish_reason": "tool_calls"
                }
            ]
        })));

        assert_eq!(events.len(), 2);
        assert!(matches!(
            &events[0],
            StreamEvent::ToolCallStart { index: 1, id, name, input }
            if id == "call_custom" && name == "draft_sql" && input == &json!("")
        ));
        assert!(matches!(
            &events[1],
            StreamEvent::ToolCallInputDelta { index: 1, partial_json }
            if partial_json == "select *"
        ));

        let response = state.into_response();
        match &response.content[0] {
            ResponseContent::ToolUse { id, name, input } => {
                assert_eq!(id, "call_custom");
                assert_eq!(name, "draft_sql");
                assert_eq!(input, &json!("select *"));
            }
            other => panic!("expected custom tool content, got {other:?}"),
        }
    }

    fn parse_chunk(value: Value) -> ChatCompletionStreamChunk {
        serde_json::from_value(value).expect("valid stream chunk")
    }

    #[test]
    fn reasoning_content_and_tagged_text_emit_reasoning_events() {
        let mut state = ChatCompletionStreamState::default();

        let events = state.apply_chunk(parse_chunk(json!({
            "id": "chatcmpl-reasoning",
            "choices": [
                {
                    "delta": {
                        "reasoning_content": "internal plan",
                        "content": "<think>hidden</think>visible"
                    },
                    "finish_reason": "stop"
                }
            ]
        })));

        assert_eq!(events.len(), 5);
        assert!(matches!(
            &events[0],
            StreamEvent::ReasoningStart { index: 1 }
        ));
        assert!(matches!(
            &events[1],
            StreamEvent::ReasoningDelta { index: 1, text } if text == "internal plan"
        ));
        assert!(matches!(
            &events[2],
            StreamEvent::ReasoningDelta { index: 1, text } if text == "hidden"
        ));
        assert!(matches!(&events[3], StreamEvent::TextStart { index: 0 }));
        assert!(matches!(
            &events[4],
            StreamEvent::TextDelta { index: 0, text } if text == "visible"
        ));

        let response = state.into_response();
        assert_eq!(response.id, "chatcmpl-reasoning");
        assert_eq!(
            response.content,
            vec![ResponseContent::Text("visible".into())]
        );
        assert_eq!(response.stop_reason, Some(StopReason::EndTurn));
        assert_eq!(response.usage, Usage::default());
        assert!(response.metadata.extras.iter().any(|extra| matches!(
            extra,
            ResponseExtra::ReasoningText { text } if text == "internal planhidden"
        )));
        assert!(response.metadata.extras.iter().any(|extra| matches!(
            extra,
            ResponseExtra::ProviderSpecific { provider, payload }
            if provider == "openai"
                && payload["choices"][0]["index"] == json!(0)
        )));
    }
}
